### ISSUE TITLE
How to run the Server?

### ISSUE THREAD

**Issue by tbarracha** [AlexanderDykov/Unity-NodeJS-Game#1]
Hello!
I am new to networking and still don't quite know how to run this server via console.
Is it meant for linux or can I just use node server.js command?

Thanks!

![image](https://user-images.githubusercontent.com/21272904/78788081-325ff100-79a3-11ea-9126-822c684d0e87.png)

**Comment by odiukov** [comment]
Hi, @Roseldine, try to run `npm install` at first and then run `node server.js` command
